chore: try running matrix in a shell
Signed-off-by: Case Wylie <cmwylie19@defenseunicorns.com>

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -68,6 +68,7 @@ jobs:
   journey:
     runs-on: ubuntu-latest
     strategy:
+      fail-fast: true
       matrix:
         test-command:
           - "npm run test:journey"
@@ -97,5 +98,10 @@ jobs:
 
       - run: npm ci
       - run: |
+          set -e # Exit immediately if a command exits with a non-zero status.
           echo "Executing: ${{ matrix.test-command }}"
-          eval ${{ matrix.test-command }} || { echo "Tests failed"; exit 1; }
+          eval ${{ matrix.test-command }}
+          if [[ $? -ne 0 ]]; then
+            echo "Tests failed: ${{ matrix.test-command }}"
+            exit 1
+          fi
