chore: login chainctl
Signed-off-by: Case Wylie <cmwylie19@defenseunicorns.com>

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -97,10 +97,18 @@ jobs:
       # - name: Chainguard Login
       #   run: |
       #     chainctl auth login --identity "${{ secrets.CHAINGUARD_IDENTITY }}" --skip-browser
-      # - name: Chainguard Login
-      #   uses: chainguard-dev/setup-chainctl@2302a56a61228140753b428d1018cb0d0addbec6 # v0.3.0
-      #   with:
-      #     identity: ${{ secrets.CHAINGUARD_IDENTITY }}
+      - name: Debug Identity Variable
+        run: |
+          if [[ -z "${{ secrets.CHAINGUARD_IDENTITY }}" ]]; then
+            echo "ERROR: CHAINGUARD_IDENTITY is missing!"
+            exit 1
+          else
+            echo "CHAINGUARD_IDENTITY is set."
+          fi
+      - name: Chainguard Login
+        uses: chainguard-dev/setup-chainctl@2302a56a61228140753b428d1018cb0d0addbec6 # v0.3.0
+        with:
+          identity: ${{ secrets.CHAINGUARD_IDENTITY }}
       - run: npm ci
       - run: ${{ matrix.journey-test }}
       - run: ${{ matrix.journey-wasm-test }}
