chore: debug CG token is set
Signed-off-by: Case Wylie <cmwylie19@defenseunicorns.com>

diff --git a/.github/workflows/pepr-excellent-examples-unicorn.yml b/.github/workflows/pepr-excellent-examples-unicorn.yml
--- a/.github/workflows/pepr-excellent-examples-unicorn.yml
+++ b/.github/workflows/pepr-excellent-examples-unicorn.yml
@@ -60,7 +60,14 @@ jobs:
         uses: chainguard-dev/setup-chainctl@2302a56a61228140753b428d1018cb0d0addbec6 # v0.3.0
         with:
           identity: ${{ secrets.CHAINGUARD_IDENTITY }}
-          
+      - name: Debug CHAINGUARD_IDENTITY
+        run: |
+          if [[ -z "${{ secrets.CHAINGUARD_IDENTITY }}" ]]; then
+            echo "CHAINGUARD_IDENTITY is missing!"
+            exit 1
+          else
+            echo "CHAINGUARD_IDENTITY is set."
+          fi
       - name: build pepr package and container image
         if: ${{ (github.event.inputs.kfcBranch || 'none') == 'none' }}
         run: |
