chore: soak test
Signed-off-by: Case Wylie <cmwylie19@defenseunicorns.com>

diff --git a/.github/workflows/soak.yaml b/.github/workflows/soak.yaml
--- a/.github/workflows/soak.yaml
+++ b/.github/workflows/soak.yaml
@@ -110,6 +110,8 @@ jobs:
         with:
           egress-policy: audit
 
+      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
+
       - name: "install k3d"
         run: "curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash"
         shell: bash
@@ -125,40 +127,86 @@ jobs:
           PEPR_TAR="${GITHUB_WORKSPACE}/pepr-img.tar"
           echo "PEPR_TAR=${PEPR_TAR}" >> "$GITHUB_ENV"
           docker image load --input "$PEPR_TAR"
+
+      - name: Create k3d Cluster
+        run: "k3d cluster create"
+        shell: bash
+
+      - name: Import pepr image into k3d
+        run: "k3d image import pepr:dev -c k3s-default"
+        shell: bash
+
+      - name: Install istioctl
+        run: |
+          curl -L https://istio.io/downloadIstio | sh -
+        shell: bash
+
+      - name: Install default profile
+        run: ./istioctl install --set profile=demo -y
+
+      - name: Set up Kubernetes
+        uses: azure/setup-kubectl@v3
+        with:
+          version: 'latest'
+
+      - name: Create logs directory
+        run: mkdir -p logs
+
+      - name: Deploy applications
+        run: |
+          kubectl apply -f hack/auditor.ci.yaml
+          kubectl apply -f hack/soak.ci.yaml
+
+      - name: Wait for 15 minutes before starting pod checks
+        run: sleep 900s  # 15 minutes
+
+      - name: Run the soak test and collect metrics
+        run: |
+          # Initialize the map to store pod counts
+          declare -A pod_map
           
-      - name: clone pepr-excellent-examples
-        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
+          update_pod_map() {
+            for pod in $(kubectl get pods -n pepr-demo -o jsonpath='{.items[*].metadata.name}'); do
+              count=${pod_map[$pod]}
+              if [ -z "$count" ]; then
+                pod_map[$pod]=1
+              else
+                pod_map[$pod]=$((count + 1))
+              fi
+            done
+          }
+
+          update_pod_map
+
+          collect_metrics() {
+            kubectl exec -it metrics-collector -n watch-auditor -- curl watch-auditor:8080/metrics | grep watch_controller_failures_total >> logs/auditor-log.txt
+            kubectl exec -it metrics-collector -n watch-auditor -- curl -k https://pepr-soak-ci-watcher.pepr-system.svc.cluster.local/metrics | egrep -E "pepr_cache_miss|pepr_resync_failure_count" >> logs/informer-log.txt
+          }
+
+          # Start collecting metrics every 5 minutes and checking pod counts every 30 minutes
+          for i in {1..27}; do  # 27 iterations cover 135 minutes (2 hours and 15 minutes)
+            collect_metrics
+            cat logs/informer-log.txt
+            cat logs/auditor-log.txt
+            if [ $((i % 6)) -eq 0 ]; then  # Every 30 minutes 
+              update_pod_map
+
+              # Verify that no pod's count exceeds 1
+              for pod in "${!pod_map[@]}"; do
+                if [ "${pod_map[$pod]}" -gt 1 ]; then
+                  echo "Test failed: Pod $pod has count ${pod_map[$pod]}"
+                  exit 1
+                fi
+              done
+            fi
+            sleep 300s  # Sleep for 5 minutes before the next iteration
+          done
+
+          echo "Soak test passed successfully!"
+ 
+
+      - name: Upload logs
+        uses: actions/upload-artifact@v3
         with:
-          repository: defenseunicorns/pepr-excellent-examples
-          path: pepr-excellent-examples
-
-      - name: "set env: PEXEX"
-        run: echo "PEXEX=${GITHUB_WORKSPACE}/pepr-excellent-examples" >> "$GITHUB_ENV"
-
-      - name: setup node
-        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
-        with:
-          node-version: 20
-          cache: "npm"
-          cache-dependency-path: pepr-excellent-examples
-
-      - name: install pepr-excellent-examples deps
-        run: |
-          cd "$PEXEX"
-          npm ci
-
-      - name: make logs directory
-        run: |
-          cd "$PEXEX"
-          mkdir logs
-          
-      - name: deploy the soak test and environment
-        run: |
-          cd "$PEXEX"
-          npm run test:soak -w hello-pepr-soak-ci -- -i pepr:dev
-
-      - name: Upload Log Output as Artifact
-        uses: actions/upload-artifact@v2
-        with:
-          name: log-output
-          path: ${{ env.PEXEX }}/logs/
+          name: soak-test-logs
+          path: logs
